server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.7.110:8848
  application:
    name: api-passenger

# redis 配置
redis_mode: "singleRedis"
redis_sentinel_nodes: 192.168.7.110:6379
redis_password: "xavier1234"
redis_database: 0
